'use client'

import { useSession } from 'next-auth/react'
import { useRouter } from 'next/navigation'
import { useEffect, useState, useCallback, useRef } from 'react'
import NotificationListener from '@/components/NotificationListener'
import MobileNav from '@/components/MobileNav'
import Sidebar from '@/components/Sidebar'
import TopBar from '@/components/TopBar'
import DashboardStats from '@/components/DashboardStats'
import DashboardSections from '@/components/DashboardSections'
import { pushNotificationService } from '@/lib/pushNotifications'
import { ChevronDown, FileText, FileSpreadsheet } from 'lucide-react'

interface DashboardStatsData {
  properties: {
    total: number
    units: number
    occupiedUnits: number
  }
  residents: {
    total: number
  }
  staff: {
    total: number
  }
  users: {
    total: number
  }
  requests: {
    open: number
    inProgress: number
    resolved: number
    total: number
    recent: number
    unassigned: number
    thisMonth: number
    frequentRequest: string
  }
  notices: {
    total: number
    published: number
    urgent: number
  }
  comments: {
    total: number
  }
}

export default function DashboardPage() {
  const { data: session, status } = useSession()
  const router = useRouter()
  const [stats, setStats] = useState<DashboardStatsData | null>(null)
  const [loading, setLoading] = useState(true)
  const [sidebarOpen, setSidebarOpen] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [showReportMenu, setShowReportMenu] = useState(false)
  const reportMenuRef = useRef<HTMLDivElement>(null)

  // Debug logging
  useEffect(() => {
    console.log('Dashboard Page Status:', {
      status,
      hasSession: !!session,
      userRole: (session?.user as { role?: string })?.role,
    })
  }, [status, session])

  // Close report menu when clicking outside
  useEffect(() => {
    const handleClickOutside = (event: MouseEvent) => {
      if (reportMenuRef.current && !reportMenuRef.current.contains(event.target as Node)) {
        setShowReportMenu(false)
      }
    }
    document.addEventListener('mousedown', handleClickOutside)
    return () => document.removeEventListener('mousedown', handleClickOutside)
  }, [])

  // Generate and download report
  const downloadReport = (format: 'pdf' | 'csv') => {
    if (!stats) {
      alert('No statistics available to download')
      return
    }

    const userName = session?.user?.name || session?.user?.email || 'User'
    const date = new Date().toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    })
    const time = new Date().toLocaleTimeString('en-US')

    if (format === 'csv') {
      // Generate CSV report
      const csvRows = [
        ['Eden Avenue Management - Dashboard Report'],
        [`Generated: ${date} ${time}`],
        [`Generated by: ${userName}`],
        [],
        ['Category', 'Metric', 'Value'],
        ['Properties', 'Total Properties', stats.properties.total],
        ['Properties', 'Total Units', stats.properties.units],
        ['Properties', 'Occupied Units', stats.properties.occupiedUnits],
        ['Residents', 'Total Residents', stats.residents.total],
        ['Staff', 'Total Staff', stats.staff.total],
        ['Users', 'Total Users', stats.users.total],
        ['Requests', 'Open Requests', stats.requests.open],
        ['Requests', 'In Progress', stats.requests.inProgress],
        ['Requests', 'Resolved', stats.requests.resolved],
        ['Requests', 'Total Requests', stats.requests.total],
        ['Requests', 'Recent (24h)', stats.requests.recent],
        ['Requests', 'Unassigned', stats.requests.unassigned],
        ['Requests', 'This Month', stats.requests.thisMonth],
        ['Requests', 'Frequent Request', stats.requests.frequentRequest],
        ['Notices', 'Total Notices', stats.notices.total],
        ['Notices', 'Published', stats.notices.published],
        ['Notices', 'Urgent', stats.notices.urgent],
        ['Comments', 'Total Comments', stats.comments.total],
      ]

      const csvContent = csvRows.map(row => row.map(cell => `"${cell}"`).join(',')).join('\n')
      const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' })
      const link = document.createElement('a')
      const url = URL.createObjectURL(blob)
      link.setAttribute('href', url)
      link.setAttribute('download', `eden-avenue-dashboard-${date.replace(/\s/g, '-')}.csv`)
      link.style.visibility = 'hidden'
      document.body.appendChild(link)
      link.click()
      document.body.removeChild(link)
    } else {
      // Generate PDF-like text report (can be printed as PDF)
      const reportContent = `
EDEN AVENUE MANAGEMENT - DASHBOARD REPORT
==========================================

Generated: ${date} ${time}
Generated by: ${userName}

PROPERTIES
----------
Total Properties: ${stats.properties.total}
Total Units: ${stats.properties.units}
Occupied Units: ${stats.properties.occupiedUnits}

RESIDENTS & STAFF
-----------------
Total Residents: ${stats.residents.total}
Total Staff: ${stats.staff.total}
Total Users: ${stats.users.total}

REQUESTS
--------
Open Requests: ${stats.requests.open}
In Progress: ${stats.requests.inProgress}
Resolved: ${stats.requests.resolved}
Total Requests: ${stats.requests.total}
Recent (24h): ${stats.requests.recent}
Unassigned: ${stats.requests.unassigned}
This Month: ${stats.requests.thisMonth}
Frequent Request: ${stats.requests.frequentRequest}

NOTICES
-------
Total Notices: ${stats.notices.total}
Published: ${stats.notices.published}
Urgent: ${stats.notices.urgent}

COMMENTS
--------
Total Comments: ${stats.comments.total}

---
Report generated by Eden Avenue Management System
      `.trim()

      // Create a new window with the report and trigger print
      const printWindow = window.open('', '_blank')
      if (printWindow) {
        printWindow.document.write(`
          <!DOCTYPE html>
          <html>
            <head>
              <title>Eden Avenue Dashboard Report</title>
              <style>
                body {
                  font-family: Arial, sans-serif;
                  padding: 40px;
                  line-height: 1.6;
                }
                pre {
                  white-space: pre-wrap;
                  font-family: 'Courier New', monospace;
                }
                @media print {
                  body { margin: 0; padding: 20px; }
                }
              </style>
            </head>
            <body>
              <pre>${reportContent}</pre>
              <script>
                window.onload = function() {
                  window.print();
                }
              </script>
            </body>
          </html>
        `)
        printWindow.document.close()
      }
    }

    setShowReportMenu(false)
  }

  const fetchStats = useCallback(async () => {
    try {
      const res = await fetch('/api/dashboard/stats', {
        method: 'GET',
        headers: {
          'Content-Type': 'application/json',
        },
        credentials: 'include', // Include cookies for authentication
      })

      if (res.ok) {
        const data = await res.json()
        console.log('Dashboard stats loaded:', data.stats)
        setStats(data.stats)
        setError(null)
      } else {
        let errorMessage = 'Failed to fetch statistics'
        let errorDetails = ''
        try {
          const errorData = await res.json()
          errorMessage = errorData.error || `HTTP ${res.status}: ${res.statusText}`
          errorDetails = errorData.details || ''

          // Provide helpful error messages
          if (res.status === 401) {
            errorMessage = 'Authentication required. Please log in again.'
          } else if (res.status === 403) {
            errorMessage = 'Access denied. Admin or Manager role required.'
          } else if (res.status === 500) {
            errorMessage = errorData.error || 'Server error. Please check server logs.'
            if (errorData.details) {
              errorDetails = errorData.details
            }
          } else if (res.status === 503) {
            errorMessage = errorData.error || 'Database connection failed'
            if (errorData.details) {
              errorDetails = errorData.details
            }
          }
        } catch {
          errorMessage = `HTTP ${res.status}: ${res.statusText}`
        }

        console.error('Failed to fetch stats:', res.status, errorMessage)
        if (errorDetails) {
          console.error('Error details:', errorDetails)
        }
        setError(errorMessage + (errorDetails ? `\n\nDetails: ${errorDetails}` : ''))

        // Set default stats if API fails
        setStats({
          properties: { total: 0, units: 0, occupiedUnits: 0 },
          residents: { total: 0 },
          staff: { total: 0 },
          users: { total: 0 },
          requests: {
            open: 0,
            inProgress: 0,
            resolved: 0,
            total: 0,
            recent: 0,
            unassigned: 0,
            thisMonth: 0,
            frequentRequest: 'N/A',
          },
          notices: { total: 0, published: 0, urgent: 0 },
          comments: { total: 0 },
        })
      }
    } catch (error) {
      const errorMsg = error instanceof Error ? error.message : 'Unknown error'
      console.error('Error fetching stats:', error)
      setError(`Network error: ${errorMsg}. Check your connection and try again.`)

      // Set default stats on error
      setStats({
        properties: { total: 0, units: 0, occupiedUnits: 0 },
        residents: { total: 0 },
        staff: { total: 0 },
        users: { total: 0 },
        requests: {
          open: 0,
          inProgress: 0,
          resolved: 0,
          total: 0,
          recent: 0,
          unassigned: 0,
          thisMonth: 0,
          frequentRequest: 'N/A',
        },
        notices: { total: 0, published: 0, urgent: 0 },
        comments: { total: 0 },
      })
    } finally {
      setLoading(false)
    }
  }, [])

  useEffect(() => {
    if (status === 'unauthenticated') {
      router.push('/auth/login')
    }
  }, [status, router])

  useEffect(() => {
    const userRole = (session?.user as { role?: string })?.role
    if (status === 'authenticated') {
      if (['ADMIN', 'MANAGER'].includes(userRole || '')) {
        fetchStats()
      } else {
        setLoading(false)
      }

      // Initialize push notifications for residents
      if (userRole === 'RESIDENT') {
        const userId = (session?.user as { id?: string })?.id
        if (userId) {
          pushNotificationService.initialize().then(initialized => {
            if (initialized) {
              pushNotificationService.requestPermission().then(permission => {
                if (permission === 'granted') {
                  pushNotificationService.subscribeToPush(userId).catch(err => {
                    console.error('Error subscribing to push notifications:', err)
                  })
                }
              })
            }
          })
        }
      }
    }
  }, [status, session, fetchStats])

  if (status === 'loading') {
    return (
      <div className="flex min-h-screen items-center justify-center bg-gray-50">
        <div className="text-center">
          <h2 className="text-4xl font-bold text-[#1e3a5f] mb-2">Eden Avenue Management</h2>
          <p className="text-gray-600">Loading...</p>
        </div>
      </div>
    )
  }

  if (status === 'unauthenticated') {
    return null // Will redirect via useEffect
  }

  const userRole = (session?.user as { role?: string })?.role || 'Unknown'

  // For non-admin/manager users, show a simplified dashboard
  if (!['ADMIN', 'MANAGER'].includes(userRole)) {
    return (
      <div className="min-h-screen bg-gray-50">
        <Sidebar isOpen={sidebarOpen} onClose={() => setSidebarOpen(false)} />
        <TopBar onMenuClick={() => setSidebarOpen(!sidebarOpen)} />
        <div className="md:ml-64 mt-16 p-4 pb-24 md:p-8 md:pb-10">
          <div className="max-w-7xl mx-auto">
            <div className="mb-8">
              <h1 className="text-3xl font-bold text-gray-800 mb-2">Dashboard</h1>
              <p className="text-gray-600">A quick data overview of your account.</p>
            </div>
            <div className="bg-white rounded-lg border border-gray-200 p-6">
              <p className="text-gray-600">
                Welcome! Use the sidebar to navigate to your requests and notices.
              </p>
            </div>
          </div>
        </div>
        <MobileNav />
      </div>
    )
  }

  // Default stats if not loaded yet
  const displayStats = stats || {
    properties: { total: 0, units: 0, occupiedUnits: 0 },
    residents: { total: 0 },
    staff: { total: 0 },
    users: { total: 0 },
    requests: {
      open: 0,
      inProgress: 0,
      resolved: 0,
      total: 0,
      recent: 0,
      unassigned: 0,
      thisMonth: 0,
      frequentRequest: 'N/A',
    },
    notices: { total: 0, published: 0, urgent: 0 },
    comments: { total: 0 },
  }

  return (
    <div className="min-h-screen bg-gray-50">
      <NotificationListener />
      <Sidebar isOpen={sidebarOpen} onClose={() => setSidebarOpen(false)} />
      <TopBar onMenuClick={() => setSidebarOpen(!sidebarOpen)} />
      <main className="md:ml-64 mt-16 p-4 pb-24 md:p-8 md:pb-10">
        <div className="max-w-7xl mx-auto">
          {/* Dashboard Header */}
          <div className="mb-8 flex flex-col md:flex-row md:items-center justify-between gap-4">
            <div>
              <h1 className="text-3xl font-bold text-gray-800 mb-2">Dashboard</h1>
              <p className="text-gray-600">A quick data overview of the property management.</p>
            </div>
            <div className="relative" ref={reportMenuRef}>
              <button
                onClick={() => setShowReportMenu(!showReportMenu)}
                className="flex items-center gap-2 px-4 py-2 bg-white border border-gray-300 rounded-lg hover:bg-gray-50 transition-colors w-full md:w-auto justify-center"
              >
                Download Report{' '}
                <ChevronDown size={16} className={showReportMenu ? 'rotate-180' : ''} />
              </button>
              {showReportMenu && (
                <div className="absolute right-0 mt-2 w-48 bg-white border border-gray-200 rounded-lg shadow-lg z-50">
                  <button
                    onClick={() => downloadReport('csv')}
                    className="w-full flex items-center gap-3 px-4 py-3 text-left hover:bg-gray-50 first:rounded-t-lg transition-colors"
                  >
                    <FileSpreadsheet size={18} className="text-green-600" />
                    <div>
                      <div className="font-medium text-sm">Download CSV</div>
                      <div className="text-xs text-gray-500">Excel compatible</div>
                    </div>
                  </button>
                  <button
                    onClick={() => downloadReport('pdf')}
                    className="w-full flex items-center gap-3 px-4 py-3 text-left hover:bg-gray-50 last:rounded-b-lg transition-colors border-t border-gray-100"
                  >
                    <FileText size={18} className="text-red-600" />
                    <div>
                      <div className="font-medium text-sm">Print PDF</div>
                      <div className="text-xs text-gray-500">Print or save as PDF</div>
                    </div>
                  </button>
                </div>
              )}
            </div>
          </div>

          {/* Error Message */}
          {error && (
            <div className="mb-8 bg-yellow-50 border border-yellow-200 rounded-lg p-4">
              <div className="flex items-start justify-between">
                <div className="flex-1">
                  <p className="text-yellow-800 text-sm font-semibold mb-1">⚠️ {error}</p>
                  <p className="text-yellow-700 text-xs mt-1">
                    Showing default values. Click retry to reload statistics.
                  </p>
                </div>
                <button
                  onClick={() => {
                    setLoading(true)
                    setError(null)
                    fetchStats()
                  }}
                  className="ml-4 px-4 py-2 bg-yellow-600 hover:bg-yellow-700 text-white text-sm rounded-lg transition-colors"
                >
                  Retry
                </button>
              </div>
              <details className="mt-2">
                <summary className="text-yellow-700 text-xs cursor-pointer">Debug Info</summary>
                <div className="mt-2 p-2 bg-yellow-100 rounded text-xs font-mono">
                  <p>User Role: {userRole}</p>
                  <p>Session Status: {status}</p>
                  <p>API Endpoint: /api/dashboard/stats</p>
                  <p className="mt-2">
                    <a
                      href="/api/dashboard/test"
                      target="_blank"
                      className="text-blue-600 hover:underline"
                    >
                      Test API Connection →
                    </a>
                  </p>
                </div>
              </details>
            </div>
          )}

          {/* Loading Indicator */}
          {loading && (
            <div className="mb-8 bg-blue-50 border border-blue-200 rounded-lg p-4">
              <p className="text-blue-800 text-sm">Loading dashboard statistics...</p>
            </div>
          )}

          {/* Key Metrics Cards */}
          <DashboardStats stats={displayStats} />

          {/* Detailed Sections */}
          <DashboardSections stats={displayStats} />
        </div>
      </main>
      <MobileNav />
    </div>
  )
}
